name: nuget-build-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
     steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.201
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./src
