name: nuget-build-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
            versionSpec: '5.x'
      - name: Determine Version
      	id: gitversion
      	uses: gittools/actions/gitversion/execute@v0.9.7
      	with:
            useConfigFile: true
            configFilePath: ./.github/gitversion.yml
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 6.0.201
      - name: Restore dependencies
        run: dotnet restore
      - name: Build dotnet 
        run: dotnet build SwaggerExampleLib.sln --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore 
      - name: Package nuget
        run: dotnet pack SwaggerExampleLib.sln --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./package/*.nupkg  --source https://nuget.pkg.github.com/mortezarezaei68/index.json   --api-key ${{ github.token }}
